export const TOGGLE_LOADER = 'SHOW_LOADER';
export const CHANGE_LOADER_TEXT = 'CHANGE_LOADER_TEXT';
export const SET_USER_INFO = 'SET_USER_INFO';
export const SIGNOUT_USER = 'SIGNOUT_USER';
export const SET_DEVICE_DATA='SET_DEVICE_DATA';
export const CHANGE_DEVICE_STATUS='CHANGE_DEVICE_STATUS';